backend:
  name: github
  repo: darayaq-01/birgit-matthias
  branch: main

local_backend: true
media_folder: "public/uploads"
public_folder: "/uploads"


collections:
  - name: "presse"
    label: "Presse"
    folder: "content/presse"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Kategorie", name: "category", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "text", required: false }
      - { label: "Veröffentlichungsdatum", name: "pubDate", widget: "datetime" }
      - { label: "Aktualisiert am", name: "updatedDate", widget: "datetime", required: false }
      - { label: "Coverbild", name: "cover", widget: "image" }
      - { label: "Alt-Text für Cover", name: "coverAlt", widget: "string" }
      - { label: "Externer Link", name: "link", widget: "string" }

  - name: "ausstellungen"
    label: "Ausstellungen"
    folder: "content/ausstellungen"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Kategorie", name: "category", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "text", required: false }
      - { label: "Veröffentlichungsdatum", name: "pubDate", widget: "datetime" }
      - { label: "Aktualisiert am", name: "updatedDate", widget: "datetime", required: false }
      - { label: "Coverbild", name: "cover", widget: "image" }
      - { label: "Alt-Text für Cover", name: "coverAlt", widget: "string" }
