backend:
  name: gitaway
  repo: darayaq-01/birgit-matthias
  branch: main
  media_folder: "/public/uploads"
  public_folder: "/uploads"
  site_url: "https://birgitmatthias-malerei.netlify.app"
  site_name: "Birgit Matthias Malerei"
  site_description: "Offizielle Website von Birgit Matthias, Malerin aus Berlin. Entdecken Sie ihre Werke, Ausstellungen und Pressemitteilungen."

collections:
  - name: "presse"
    label: "Presse"
    folder: "content/presse"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Kategorie", name: "category", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "text", required: false }
      - { label: "Veröffentlichungsdatum", name: "pubDate", widget: "datetime" }
      - { label: "Aktualisiert am", name: "updatedDate", widget: "datetime", required: false }
      - { label: "Coverbild", name: "cover", widget: "image" }
      - { label: "Alt-Text für Cover", name: "coverAlt", widget: "string" }
      - { label: "Externer Link", name: "link", widget: "string" }

  - name: "ausstellungen"
    label: "Ausstellungen"
    folder: "content/ausstellungen"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Kategorie", name: "category", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "text", required: false }
      - { label: "Veröffentlichungsdatum", name: "pubDate", widget: "datetime" }
      - { label: "Aktualisiert am", name: "updatedDate", widget: "datetime", required: false }
      - { label: "Coverbild", name: "cover", widget: "image" }
      - { label: "Alt-Text für Cover", name: "coverAlt", widget: "string" }
